Fsx for lustre added as module to Karpenter example
awslabs/data-on-eks pull request #139
Opened 2023-03-17 10:07 UTC by vara-bonthu

### What does this PR do?

🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted.
Consult the [CONTRIBUTING](https://github.com/awslabs/data-on-eks/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guide for submitting pull-requests.

- RAID0 config added to Karpenter examples
- FSx for Lustre as a sub module for Karpenter. FSx for Lustre blueprint will be removed later
- Workshop folder structure created

### Motivation

### More

- [ ] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/awslabs/data-on-eks/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR to add a new Add-on for [Terraform EKS Blueprints](https://github.com/aws-ia/terraform-aws-eks-blueprints) repo (if applicable)
- [ ] Yes, I have updated the `website/docs` or `website/blog` section for this feature
- [ ] Yes, I ran `pre-commit run -a` with this PR. Link for installing [pre-commit](https://pre-commit.com/) locally

### For Moderators

- [ ] E2E Test successfully complete before merge?

### Additional Notes

2023-03-17 13:27 UTC, dalbhanj requested changes
I left comment on create FSx piece of infrastructure separate and available on-demand when users want to use it rather than part of the whole infrastructure setup. Please take a look. Thanks!

2023-03-17 13:27 UTC, dalbhanj commented on analytics/terraform/emr-eks-karpenter/modules/fsx-for-lustre/fsx_lustre/fsxlustre-static-pvc.yaml
Same here...

2023-03-17 13:27 UTC, dalbhanj commented on analytics/terraform/emr-eks-karpenter/modules/fsx-for-lustre/fsx_lustre/fsxlustre-storage-class.yaml
We can probably get away with this one as I understand FSx volume gets created when you create a PVC

2023-03-17 13:27 UTC, dalbhanj commented on analytics/terraform/emr-eks-karpenter/variables.tf
This looks good and provides better experience for customers!

2023-03-20 15:35 UTC, vara-bonthu commented on analytics/terraform/emr-eks-karpenter/modules/fsx-for-lustre/fsx_lustre/fsxlustre-dynamic-pvc.yaml
This is now a separate module

2023-03-20 15:35 UTC, vara-bonthu commented on analytics/terraform/emr-eks-karpenter/modules/fsx-for-lustre/fsx_lustre/fsxlustre-static-pvc.yaml
updated

2023-03-20 15:37 UTC, merged