[enhancement] update argo workflows based on blog comments
awslabs/data-on-eks pull request #89
Opened 2023-01-03 20:37 UTC by season1946

### What does this PR do?

🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted.
Consult the [CONTRIBUTING](https://github.com/awslabs/data-on-eks/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guide for submitting pull-requests.

### Motivation

### More

- [ ] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/awslabs/data-on-eks/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR to add a new Add-on for [Terraform EKS Blueprints](https://github.com/aws-ia/terraform-aws-eks-blueprints) repo (if applicable)
- [ ] Yes, I have updated the `website/docs` or `website/blog` section for this feature
- [ ] Yes, I ran `pre-commit run -a` with this PR. Link for installing [pre-commit](https://pre-commit.com/) locally

### For Moderators

- [ ] E2E Test successfully complete before merge?

### Additional Notes

2023-01-03 23:26 UTC, vara-bonthu requested changes
Few comments to address otherwise it's good 👍🏼

2023-01-03 23:26 UTC, vara-bonthu commented on schedulers/terraform/argo-workflow/helm-values/aws-for-fluentbit-values.yaml
> +  autoCreateGroup: true
change this to `autoCreateGroup: false`

2023-01-03 23:26 UTC, vara-bonthu commented on schedulers/terraform/argo-workflow/argo-events/sensor-sqs-sparkjobs.yaml
> +                  - - name: hello1
Is this ok with two hyphens?

2023-01-03 23:26 UTC, vara-bonthu commented on schedulers/terraform/argo-workflow/argo-events/sensor-sqs-sparkjobs.yaml
> +                  - - name: spark-work
same here with two hyphens?

2023-01-03 23:41 UTC, season1946 commented on schedulers/terraform/argo-workflow/helm-values/aws-for-fluentbit-values.yaml
> +  autoCreateGroup: true
changed to false

2023-01-04 00:01 UTC, vara-bonthu reviewed
few more changes to be udpated

2023-01-04 00:33 UTC, vara-bonthu approved these changes
Thanks! LGTM 👍🏼

2023-01-04 00:34 UTC, merged